apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-registryd
  labels:
    app.kubernetes.io/name: registryd
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: registryd
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: api
      port: {{ .Values.service.apiPort }}
      targetPort: api
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
